[versions]
android-minSdk = "28"
android-compileSdk = "34"
agp = "8.2.2"
kotlin = "1.9.22"
compose = "1.5.12"
styx-common = "0.0.1"
voyager = "1.0.0"
multiplatform-settings = "1.1.1"
kamel = "0.9.2"
kstore = "0.7.1"
mordant = "2.3.0"
oshi = "6.4.11"


[libraries]
styx-common = { module = "moe.styx:styx-common", version.ref = "styx-common" }
voyager-nav = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-screenmodel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-tabnav = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-bottomsheetnav = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }
kamel-image = { module = "media.kamel:kamel-image", version.ref = "kamel" }
kstore = { module = "io.github.xxfast:kstore", version.ref = "kstore" }
kstore-file = { module = "io.github.xxfast:kstore-file", version.ref = "kstore" }
jvm-mordant = { module = "com.github.ajalt.mordant:mordant-jvm", version.ref = "mordant" }
jvm-oshi = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }


[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
